# tasks file for mysql_db
    - name: Install MySQL Database
      yum: name={{ item }} state=installed
      with_items:
        - mysql-server
        - mysql


    - name: Start MySQL Service
      service:
        name: mysqld.service
        state: started
        enabled: yes

    - name: Create a new database with name employee_db
      community.mysql.mysql_db:
        name: "{ { db_name } }"
        state: present

    - name: Create database user with name 'db_user' and password 'Passw0rd' with all database privileges
      community.mysql.mysql_user:
        name: "{ { db_user_name } }"
        password: "{ { db_user_password } }"
        priv: 'employee_db.*:ALL'
        state: present
